version: '2'
services:
  consul:
    image: consul:0.7.2
    restart: always
    dns:
      - 127.0.0.1
    ports:
      - "8500:8500"
    command: agent -server -client=0.0.0.0 -bootstrap -ui
  db:
    build: ./db
    restart: always
    environment:
      - CONSUL_HOST=consul
 #   ports:
 #     - "27017:27017"
  kafka:
    build: ./kafka
    restart: always
    environment:
      - CONSUL_HOST=consul
      - BANK_CODE=FJI

  rabbit:
    build: ./rabbit
    restart: always
    environment:
      - HOSTNAME=${DOCKER_HOST}
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"

  api:
    build: ./api
    restart: always
    environment:
      - CONSUL_HOST=consul
      - BANK_CODE=FJI
#    ports:
#      - "1337:1337"
